apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore  # Changed from SecretStore to ClusterSecretStore
metadata:
  name: aws-secretsmanager
spec:
  controller: ""
  provider:
    aws:
      auth:
        jwt:
          serviceAccountRef:
            name: ${serviceaccount}
            namespace: ${namespace}
      region: ${region}
      service: SecretsManager
  refreshInterval: 0
