##
# call-renovate-jira.yaml
# Calls remote workflow to create Jira issue for Renovate Bot pull request.
##
---
    name: Call remove workflow to create Jira issue for Renovate Bot pull request
    on:
      pull_request:
        types: [opened]
    
    jobs:
      call-common-workflow:
        name: Create Jira issue for Renovate PR
        uses: DRE-IaC/github-workflow-common/.github/workflows/renovate-jira.yaml@master
        secrets: inherit
        permissions:
          pull-requests: read
          contents: read
          issues: none
          packages: none
          deployments: none
