name: Terraform CI/CD

on:
  push:
    branches: master
  workflow_dispatch:

env:
  AWS_REGION: us-east-1  # Update with your AWS region
  TF_VERSION: 1.5.0      # Update with your Terraform version

jobs:
  terraform:
    name: Terraform 
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: arn:aws:iam::344565808703:role/controlplane
        aws-region: ${{ env.AWS_REGION }}
        
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ env.TF_VERSION }}
    
    - name: Check AWS identity
      run: |
        aws sts get-caller-identity
        echo "Repository: ${{ github.repository }}"
        echo "Ref: ${{ github.ref }}"
        
    - name: Terraform Init
      run: |
        terraform init \
          -backend-config="bucket=use2-iac-controlplane-tf-states-snarrabelly" \
          -backend-config="key=env:/primary/terraform.tfstate" \
          -backend-config="region=${{ env.AWS_REGION }}" \
          -backend-config="dynamodb_table=use2-iac-controlplane-tf-state-lock"
      
    - name: Terraform Format
      run: terraform fmt -check
      
    - name: Terraform Validate
      run: terraform validate
      
    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color
      
    - name: Terraform Apply
      if: github.ref == 'refs/heads/master'
      run: terraform apply -auto-approve