name: Infrastructure Control Plane CI/CD

on:
  push:
    branches: 
      - master

env:
  GITHUB_BASE_URL: https://github.com/DRE-IaC/
  REPOSITORY_NAME: pipeline-testing
  AWS_REGION: us-east-2
  AWS_ROLE_ARN: arn:aws:iam::344565808703:role/controlplane

permissions:
  id-token: write
  contents: read
  actions: write

jobs:
  plan:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Simulate Terraform Plan
        run: |
          echo "Simulating Terraform Plan"
          mkdir -p plan_output
          echo "Dummy plan content" > plan_output/terraform.tfplan
          exit 0  # Ensure this step always passes

      - name: Upload plan artifacts
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: plan_output/terraform.tfplan

  wait-for-approval:
    needs: plan
    runs-on: ubuntu-latest
    steps:
      - name: Approve or Reject
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.token }}
          approvers: org-admins
          minimum-approvals: 1
          issue-title: "Approve Infrastructure Deployment"
          issue-body: "Please review and approve the infrastructure changes."

  apply:
    needs: [plan, wait-for-approval]
    runs-on: ubuntu-latest
    if: ${{ needs.wait-for-approval.outputs.approval-status == 'approved' }}
    
    steps:
      - name: Print Deployment Message
        run: |
          echo "🚀 Deployment Approved!"
          echo "Initiating infrastructure deployment..."
          echo "Checking pre-deployment conditions..."
          echo "Validating configuration settings..."
          echo "Preparing resources for deployment..."
          echo "Deployment in progress..."
          echo "Infrastructure deployment completed successfully! 🎉"