name: Infrastructure Control Plane CI/CD

on:
  push:
    branches: master

env:
  GITHUB_BASE_URL: https://github.com/DRE-IaC/
  REPOSITORY_NAME: pipeline-testing
  AWS_REGION: us-east-2
  AWS_ROLE_ARN: arn:aws:iam::344565808703:role/controlplane

permissions:
  id-token: write   # Required for OIDC
  contents: read    # Required to checkout the repository

jobs:
  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    outputs:
      plan-status: ${{ steps.plan.outcome }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Run Terraform Plan
        id: plan
        run: |
          ./tf.sh -e primary -a plan --code-pipeline on

      - name: Upload plan artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: plan.out  # Replace with actual plan output file

  manual-approval:
    name: Manual Approval
    needs: plan
    runs-on: ubuntu-latest
    steps:
      - name: Wait for Manual Approval
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          required-reviewers: "your-username" # Replace with actual GitHub username

  apply:
    name: Terraform Apply
    needs: manual-approval
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Download plan artifact
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan
          path: .

      - name: Run Terraform Apply
        run: |
          ./tf.sh -e primary -a apply --code-pipeline on
