name: Run renovate bot
on:
  workflow_call:
    inputs:
      logLevel:
        description: 'Override default log level'
        type: string
        required: false
        default: 'info'
      includePaths:
        description: 'The list of paths to include in renovation'
        required: true
        type: string
concurrency: renovate

jobs:
  renovate:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check required secrets
        run: |
          if [ -z '${{ secrets.RENOVATE_APP_ID }}' ] || [ -z '${{ secrets.RENOVATE_PRIVATE_KEY }}' ]; then
            echo 'Error: Required secrets are not set'
            exit 1
          fi

      - name: Get token
        id: app-token
        continue-on-error: false
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.RENOVATE_APP_ID }}
          private-key: ${{ secrets.RENOVATE_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v41.0.13
        env:
          # Onboarding not needed for self hosted
          RENOVATE_ONBOARDING: 'false'
          # Username for GitHub authentication
          RENOVATE_USERNAME: 'dre-iac-renovate[bot]'
          # Git commit author used, must match GitHub App
          RENOVATE_GIT_AUTHOR: 'dre-iac-renovate <1152757+dre-iac-renovate[bot]@users.noreply.github.com>'
          # This allows for signed commits from GitHub App
          RENOVATE_PLATFORM_COMMIT: 'true'
          # Log level for Renovate
          LOG_LEVEL: ${{ inputs.logLevel || 'info' }}
          # Disable autodiscovery to prevent scanning eks-platform repos
          RENOVATE_AUTODISCOVER: 'false'
          # Explicitly specify the percipio-bom repository
          RENOVATE_REPOSITORIES: 'DRE-IaC/percipio-bom'
          # Include paths from input parameter
          RENOVATE_INCLUDE_PATHS: ${{ inputs.includePaths || '' }}
        with:
          token: '${{ steps.app-token.outputs.token }}'

      - name: Check job status
        if: always()
        run: |
          if [ '${{ job.status }}' != 'success' ]; then
            echo 'Job failed or had warnings'
            exit 1
          fi